### ISSUE TITLE
[Feature request] Print job end time(date)

### ISSUE THREAD

**Issue by MichaelJ2600** [jellespijker/home-assistant-ultimaker#14] opened 2022-04-25 19:22 UTC
Hello

Thank you for a very nice add-in, that I Enjoy very much. 
What I miss is the timestamp for completion of the printjob. It is there in the Android App, and in Cura (monitor/web view), so I would guess its somewhere to finde via the API you are accessing too ?

Michael

**Comment by jellespijker** [comment] 2022-04-26 05:17
I like hearing that you enjoy the add-on.

This has been wish of mine as well, unfortunately I'm a bit pressed for time to implement this a.t.m. it's coming I just don't know when yet.

It looks like a duplicate of #12 so I will close this issue in favor of that ticket

**Closed as completed by jellespijker** 2022-04-26 05:17 UTC
